query reposQuery {
    user(login: "DmitriyPavlovskyi"){
        repositories(first: 50){
            nodes{
                name
                id
            }
            pageInfo{
                hasNextPage
            }
        }
      }
}
